apiVersion: apps/v1
kind: Deployment
##metadata contains the labels spec contains selectors
metadata:
  name: $PROJECT_NAME
  labels:
    app: $PROJECT_NAME
##specification for deployment(desired not the status status inside etcd)
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: $PROJECT_NAME
  ##spec for pod( the spec that i want (desired))
  template:
    metadata:
      labels:
        app : $PROJECT_NAME
    spec:
      imagePullSecrets:
        - name : docker-registry-key
      containers:
      - name : $PROJECT_NAME
        image: $DOCKER_IMAGE_NAME:$IMAGE_TAG
        imagePullPolicy: Always
        ports:  
        - containerPort: 3002
        env:
        - name: DB_HOST
          value: mysql-primary
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          value: secret-root-pwd
        - name: DB_NAME
          value: auctiondb
        - name: DB_PORT
          value: "3306"
        - name: BID_PORT
          value: "3002"
        - name: BID_SERVER
          value: "194-195-247-34.ip.linodeusercontent.com"
        - name: CLIENT_PORT
          value: "80"
        - name: CLIENT
          value: "194-195-247-34.ip.linodeusercontent.com"
